theme = 'rose_pine_dawn'

[editor]
shell = ["zsh", "-c"]
cursorline = true
cursorcolumn = true
bufferline = "always"
color-modes = true
text-width = 120

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.whitespace.render]
tab = "all"
nbsp = "all"

[editor.whitespace.characters]
tab = "→"
tabpad = "·"
nbsp = "·"

[editor.indent-guides]
render = true
character = "┆"

[editor.soft-wrap]
enable = true

[keys.normal.space.space]
# Open the github UI for the given line
# But note this expects a path relative to the repo root
# and buffer_name is just the path that's open.
g = { o = ":sh gh browse \"%{buffer_name}:%{cursor_line}\""}
left = "jump_view_left"
A-left = "swap_view_left"
right = "jump_view_right"
A-right = "swap_view_right"
up = "jump_view_up"
A-up = "swap_view_up"
down = "jump_view_down"
A-down = "swap_view_down"
