"$schema"="https://gitlab.com/Lanastara/lanastara_foss/-/raw/v0.3.0/schema.json?ref_type=tags"
# Text that will be printed between each Module.
module_separator = " "
# Controls whether colors are reset at the end of output.
# Try this if your prompt displays a blank space at the end.
# reset_color = true
# Timeout after wich the process is teminated.
# timeout = 1000
 
# Note that you can change the order of the modules on your prompt
# by changing their order in this config file.

# Controls the behaviour of the bookmark finding algorithm.
[bookmarks]
# Exclude certain bookmarks from the search (supports globs); takes a list of strings.
# Example: `exclude = ["feature branch"]`
exclude = []
# Controls how far we are looking back to find bookmarks.
# search_depth = 0

[[module]]
# Prints information about bookmarks in the working copy's ancestors.
type = "Bookmarks"
# Text that will be rendered between each bookmark.
separator = " "
# Color the text will be rendered in. One of Black, Red, Green, Yellow, Blue, Magenta, Cyan, White,
# BrightBlack, BrightRed, BrightGreen, BrightYellow, BrightBlue, BrightMagenta, BrightCyan, BrightWhite
color = "Magenta"
# True RGB Color can also be used like this. Do not use both color and color.TrueColor at the same time!
# color.TrueColor = [255, 255, 255]
# Text background color. Can also be TrueColor.
# bg_color = "Yellow"
# A suffix that will be printed when the given bookmark is behind the working copy.
behind_symbol = "⇡"
# Ignore Commits without a description.
# Possible values: None, Current, All
# None=> [default] Count all commits even ones without description
# Current => Don't count the current commit if it's description is empty
# All => Don't count any commits without description
# ignore_empty_commits = "None"
# Maximum amount of bookmarks that will be rendered.
# max_bookmarks = 1
# Maximum length the bookmark name will be truncated to.
# max_length = 10
# Surround the bookmark names with double-quotes
# surround_with_quotes = true

# [[module]]
# # Prints the working copy's commit text.
# type = "Commit"
# # Maximum length the commit text will be truncated to.
# max_length = 24

# # color = "Green"

# # bg_color = "Yellow"

# # default text if the commit description is not set
# # empty_text = "(no description set)"

# # Surround the commit text with double-quotes
# # surround_with_quotes = true

# # Show the previous commits description in case current is empty
# # This will also print the previous_message_symbol
# # show_previous_if_empty= false

# # A prefix that will be printed when the current commit is empty and the previous commit is shown
# previous_message_symbol="⇣"

# # Controls if and how the Change Id should be shown
# [module.change]
# # fg = "magenta"

# # Controls if and how the Commit Id should be shown
# [module.commit]
# # fg = "blue"

[[module]]
# Prints a warning if the working copy contains any conflicts, is divergent, hidden, immutable, or empty.
type = "State"
# Text that will be printed between each warning.
separator = " "

[module.conflict]
text = "(CONFLICT)"
color = "Red"
# bg_color = "Yellow"

[module.divergent]
text = "(DIVERGENT)"
color = "Cyan"
# bg_color = "Yellow"

[module.hidden]
text = "(HIDDEN)"
color = "Yellow"
# bg_color = "Yellow"

[module.immutable]
disabled = false
text = "(IMMUTABLE)"
color = "Yellow"

[module.empty]
disabled = false
text = "(EMPTY)"
color = "Yellow"

[[module]]
# Prints the amount of changes in the working copy.
type = "Metrics"
# Hide the metrict module in case there are no changes [0 +0-0]
# hide_if_empty = true
color = "Magenta"
# bg_color = "Yellow"
# Controls how the changes are rendered. Use {added}, {removed} and {changed} to render the number of changes.
template = "[{changed} {added}{removed}]"

[module.changed_files]
# Controls how the number of changed files is rendered.
# suffix = ""
# prefix = ""
color = "Cyan"
# bg_color = "Yellow"

[module.added_lines]
# Controls how the number of added lines is rendered.
prefix = "+"
# suffix = ""
color = "Green"
# bg_color = "Yellow"

[module.removed_lines]
# Controls how the number of removed lines is rendered.
prefix = "-"
# suffix = ""
color = "Red"
# bg_color = "Yellow"

